server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:

        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product/**

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
