# ==============================
# SERVER
# ==============================
server.port=8080

# ==============================
# H2 DATABASE (Order DB)
# ==============================
spring.datasource.h2.jdbc-url=jdbc:h2:mem:orderdb
spring.datasource.h2.driver-class-name=org.h2.Driver
spring.datasource.h2.username=sa
spring.datasource.h2.password=

spring.jpa.h2.hibernate.ddl-auto=update
spring.jpa.h2.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


# ==============================
# POSTGRES DATABASE (User + Address DB)
# ==============================
spring.datasource.postgres.jdbc-url=jdbc:postgresql://localhost:5432/JPA
spring.datasource.postgres.driver-class-name=org.postgresql.Driver
spring.datasource.postgres.username=postgres
spring.datasource.postgres.password=JOHNcena

spring.jpa.postgres.hibernate.ddl-auto=update
spring.jpa.postgres.database-platform=org.hibernate.dialect.PostgreSQLDialect
